### ISSUE TITLE
When running learn test - after adding the hidden element to the index.html form - it marks my lab as passing even though I haven't added code to my main.js file yet.

### ISSUE THREAD

**Issue by daliayan** [learn-co-curriculum/fewpjs-build-the-example#14]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

Add a link to the assignment in Canvas here.

https://learning.flatironschool.com/courses/2072/assignments/68853?module_item_id=134064

## Describe the bug

Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

When running learn test - after adding the hidden element to the index.html form - it marks my lab as passing even though I haven't added code to my main.js file yet.

## What is the expected behavior?

Write a clear and concise description of what you expected to happen.

I expected to see the rest of the errors in my lab.

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [x] WSL
- [ ] Linux

**Comment by ihollander** [comment]
Hi @daliayan, thanks for your feedback! I made an [edit to the readme](https://github.com/learn-co-curriculum/fewpjs-build-the-example/commit/2cebf6376b66b3f500dbde2e4c50ffe687456be1) that clarifies there aren't tests for this lesson for your JavaScript code, and you'll need to check your work by running the application in the browser. Because this particular lesson uses randomization to mimic a server failure, it's not possible to write a good test that check for "random" behavior like this - this would be considered a ["non-deterministic" test](https://martinfowler.com/articles/nonDeterminism.html#:~:text=A%20test%20is%20non%2Ddeterministic,such%20tests%20are%20seemingly%20random.).
